### ISSUE TITLE
Create a web interface for chess analysis

### ISSUE THREAD

**Issue by TerranceKhumalo** [TerranceKhumalo/angular-theme#1]
# Issue 1: Create a web interface for chess analysis and commentary
## Description
The goal of this issue is to create a web interface that allows users to **play chess against a chess engine**, **upload their own games or master games**, and **get natural language explanations for the moves**. The web interface should have the following features:

- A chess board that displays the current position and the moves
- A move list that shows the moves and the commentary for each move
- A control panel that allows users to start a new game, upload a game, undo or redo moves, change the board orientation, etc.
- A settings panel that allows users to customize the board appearance, the engine strength, the commentary style, etc.

## Tasks
- [x] Design and implement the HTML and CSS layout for the web interface
- [ ] Use a JavaScript library such as [chessboard.js](https://chessboardjs.com/) or [chess.js](https://github.com/jhlywa/chess.js) to create and manipulate the chess board and the move list
- [ ] Use a JavaScript library such as [stockfish.js](https://github.com/nmrugg/stockfish.js) or [chess-engine.js](https://github.com/lhartikk/chess-engine) to integrate a chess engine into the web interface
- [ ] Use a JavaScript library such as [axios](https://github.com/axios/axios) or [fetch](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API) to communicate with the backend API for getting natural language explanations
- [ ] Test and debug the web interface using various browsers and devices
